[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = [
  'cd backend && npm run build',
  'cd backend && OPENSSL_CONF=/dev/null npm run prisma:generate'
]

[start]
cmd = 'cd backend && npm run start:prod'

[variables]
NODE_ENV = 'production'
OPENSSL_CONF = '/dev/null'