[phases.setup]
nixPkgs = ['nodejs_18', 'openssl_1_1', 'pkg-config']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = [
  'cd backend && npm run build',
  'cd backend && OPENSSL_CONF=/dev/null npm run prisma:generate --generator client'
]

[start]
cmd = 'cd backend && npm run start:prod'

[variables]
NODE_ENV = 'production'
OPENSSL_CONF = '/dev/null'
LD_LIBRARY_PATH = '/nix/store/*-openssl-1.1*/lib'