[phases.setup]
nixPkgs = ['nodejs_18', 'openssl', 'postgresql']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'npm run build',
  'PRISMA_CLI_BINARY_TARGETS=debian-openssl-1.1.x npm run prisma:generate'
]

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'
PRISMA_CLI_BINARY_TARGETS = 'debian-openssl-1.1.x'